tasks:
  - init: flutter pub get
    command: flutter run -d web --web-hostname 0.0.0.0 --web-port 8080

ports:
  - port: 8080
    onOpen: open-browser

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - Dart-Code.dart-code@3.9.0:umvoqCQMs3NpksmwhVtStw==
    - Dart-Code.flutter@3.9.0:rhf4nv+I5pjwQEks5HXkDg==